import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

// Exported as a variable rather than inline so the array has a name in stack
// traces and the anonymous-default-export rule has nothing to say.
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // All generated by `next build`, all gitignored. Linting the framework's own
  // output only means `npm run lint` passes before a build and fails after one:
  // next-env.d.ts breaks next/typescript's triple-slash rule, and the compiled
  // bundles are thousands of require() calls.
  //
  // .next-verify is the same output under the name NEXT_DIST_DIR gives it, so
  // that a build run to check a change does not overwrite the directory a
  // running `next dev` is serving from. See next.config.ts.
  {
    ignores: [
      ".next/**",
      ".next-verify/**",
      "node_modules/**",
      "next-env.d.ts",
    ],
  },
];

export default config;
